- name: Provision PostgreSQL RDS Instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create RDS instance
      community.aws.rds_instance:
        engine: postgres
        db_instance_identifier: "{{ db_instance_identifier }}"
        allocated_storage: 20
        db_instance_class: db.t2.micro
        engine_version: "12.4"
        master_username: "{{ master_username }}"
        master_user_password: "{{ master_user_password }}"
        multi_az: False
        publicly_accessible: True
        state: present
